name: Trigger auto deployment for azhk-git-app-aca-t

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/azhk-git-app-aca-t-AutoDeployTrigger-523360eb-5edb-449a-b244-e3a833e17864.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZHKGITAPPACAT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZHKGITAPPACAT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZHKGITAPPACAT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: azhkgitappacrt.azurecr.io
          registryUsername: ${{ secrets.AZHKGITAPPACAT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.AZHKGITAPPACAT_REGISTRY_PASSWORD }}
          containerAppName: azhk-git-app-aca-t
          resourceGroup: AZHK-GIT-APP-RG-ShareRes
          imageToBuild: azhkgitappacrt.azurecr.io/azhk-git-app-aca-t:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


