name: Build and Push Nginx to ACR

on:
  push:
    branches:
      - main  # Runs when changes are pushed to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Log in to Azure
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_PROD_CREDENTIALS }}

      # Log in to Azure Container Registry
      - name: Log in to ACR
        run: az acr login --name ${{ secrets.ACR_PROD_NAME }}

      # Build and Push Docker Image to ACR
      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=${{ secrets.ACR_PROD_NAME }}.azurecr.io/nginx:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
        
      - name: Log out of Prod Tenant
        run: az logout