name: Deploy Nginx to Azure Container App

on:
  workflow_run:
    workflows: ["Build and Push Nginx to ACR"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Image Info Artifact
        uses: actions/download-artifact@v3
        with:
          name: image-info
          path: .

      - name: Read Image Name
        run: echo "IMAGE_NAME=$(cat image-info.txt)" >> $GITHUB_ENV

      - name: Azure Login (Prod Tenant - Container App)
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_PROD }}

      - name: Deploy to Azure Container Apps
        run: |
          az containerapp update \
            --name ${{ secrets.CONTAINER_APP_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --image $IMAGE_NAME \
            --registry-server ${{ secrets.ACR_NAME }}.azurecr.io \
            --registry-username ${{ secrets.ACR_CLIENT_ID }} \
            --registry-password ${{ secrets.ACR_CLIENT_SECRET }}
